<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="49" started-at="2023-06-28T09:23:11Z" finished-at="2023-06-28T09:23:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="49" started-at="2023-06-28T09:23:11Z" finished-at="2023-06-28T09:23:11Z">
      <class name="annot.Annot">
        <test-method status="PASS" signature="testCase1()[pri:0, instance:annot.Annot@100fc185]" name="testCase1" duration-ms="14" started-at="2023-06-28T09:23:11Z" finished-at="2023-06-28T09:23:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase1 -->
        <test-method status="SKIP" signature="testCase2()[pri:0, instance:annot.Annot@100fc185]" name="testCase2" duration-ms="1" started-at="2023-06-28T09:23:11Z" finished-at="2023-06-28T09:23:11Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Reason for skipping this testCase]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Reason for skipping this testCase
at annot.Annot.testCase2(Annot.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method status="PASS" signature="testCase3()[pri:0, instance:annot.Annot@100fc185]" name="testCase3" duration-ms="1" started-at="2023-06-28T09:23:11Z" finished-at="2023-06-28T09:23:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase3 -->
      </class> <!-- annot.Annot -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
